- hosts: 172.31.31.33
  become: True
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Start and enable apache
      service:
        name: httpd
        state: started
        enabled: Yes
    - name: copy html code to apache
      copy:
        src: index.html
        dest: /var/www/html/