- hosts: 172.31.31.33
  become: 
  tasks:
   - name : install apache
     yum  :
      name: httpd
      state: present
   - name: start and enable apache
      service:
      name: httpd
      state: started
      enabled: yes
   - name: copy html code to apache
     copy:
     src: index.html
     dest: /var/www/html